version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: benchmark-rabbitmq
    restart: always
    expose:
      - 5672
      - 15672
    ports:
      - 5670:5672
      - 15670:15672
    networks:
      - microservicesnet
networks:
  microservicesnet:
    driver: bridge