version: '3.3'

services:
  redis:
    image: 'bitnami/redis:6.2'
    container_name: redis-rabbitmq
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes